// This file was automatically generated by lister-gen

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	v1alpha1 "k8s.io/bgd/pkg/apis/controller/v1alpha1"
	"k8s.io/client-go/tools/cache"
)

// BlueGreenDeploymentLister helps list BlueGreenDeployments.
type BlueGreenDeploymentLister interface {
	// List lists all BlueGreenDeployments in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.BlueGreenDeployment, err error)
	// BlueGreenDeployments returns an object that can list and get BlueGreenDeployments.
	BlueGreenDeployments(namespace string) BlueGreenDeploymentNamespaceLister
	BlueGreenDeploymentListerExpansion
}

// blueGreenDeploymentLister implements the BlueGreenDeploymentLister interface.
type blueGreenDeploymentLister struct {
	indexer cache.Indexer
}

// NewBlueGreenDeploymentLister returns a new BlueGreenDeploymentLister.
func NewBlueGreenDeploymentLister(indexer cache.Indexer) BlueGreenDeploymentLister {
	return &blueGreenDeploymentLister{indexer: indexer}
}

// List lists all BlueGreenDeployments in the indexer.
func (s *blueGreenDeploymentLister) List(selector labels.Selector) (ret []*v1alpha1.BlueGreenDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BlueGreenDeployment))
	})
	return ret, err
}

// BlueGreenDeployments returns an object that can list and get BlueGreenDeployments.
func (s *blueGreenDeploymentLister) BlueGreenDeployments(namespace string) BlueGreenDeploymentNamespaceLister {
	return blueGreenDeploymentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BlueGreenDeploymentNamespaceLister helps list and get BlueGreenDeployments.
type BlueGreenDeploymentNamespaceLister interface {
	// List lists all BlueGreenDeployments in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.BlueGreenDeployment, err error)
	// Get retrieves the BlueGreenDeployment from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.BlueGreenDeployment, error)
	BlueGreenDeploymentNamespaceListerExpansion
}

// blueGreenDeploymentNamespaceLister implements the BlueGreenDeploymentNamespaceLister
// interface.
type blueGreenDeploymentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BlueGreenDeployments in the indexer for a given namespace.
func (s blueGreenDeploymentNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BlueGreenDeployment, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BlueGreenDeployment))
	})
	return ret, err
}

// Get retrieves the BlueGreenDeployment from the indexer for a given namespace and name.
func (s blueGreenDeploymentNamespaceLister) Get(name string) (*v1alpha1.BlueGreenDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("bluegreendeployment"), name)
	}
	return obj.(*v1alpha1.BlueGreenDeployment), nil
}
