// This file was automatically generated by lister-gen

package v1alpha1

// BlueGreenDeploymentListerExpansion allows custom methods to be added to
// BlueGreenDeploymentLister.
type BlueGreenDeploymentListerExpansion interface{}

// BlueGreenDeploymentNamespaceListerExpansion allows custom methods to be added to
// BlueGreenDeploymentNamespaceLister.
type BlueGreenDeploymentNamespaceListerExpansion interface{}
