// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "k8s.io/bgd/pkg/client/informers_generated/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BlueGreenDeployments returns a BlueGreenDeploymentInformer.
	BlueGreenDeployments() BlueGreenDeploymentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BlueGreenDeployments returns a BlueGreenDeploymentInformer.
func (v *version) BlueGreenDeployments() BlueGreenDeploymentInformer {
	return &blueGreenDeploymentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
