// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenDeployment) DeepCopyInto(out *BlueGreenDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenDeployment.
func (in *BlueGreenDeployment) DeepCopy() *BlueGreenDeployment {
	if in == nil {
		return nil
	}
	out := new(BlueGreenDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueGreenDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenDeploymentList) DeepCopyInto(out *BlueGreenDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlueGreenDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenDeploymentList.
func (in *BlueGreenDeploymentList) DeepCopy() *BlueGreenDeploymentList {
	if in == nil {
		return nil
	}
	out := new(BlueGreenDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueGreenDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenDeploymentSpec) DeepCopyInto(out *BlueGreenDeploymentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenDeploymentSpec.
func (in *BlueGreenDeploymentSpec) DeepCopy() *BlueGreenDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(BlueGreenDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenDeploymentStatus) DeepCopyInto(out *BlueGreenDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenDeploymentStatus.
func (in *BlueGreenDeploymentStatus) DeepCopy() *BlueGreenDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(BlueGreenDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
